version: '3'

services: 
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500
    ports:
      - 1521:1521
      - 5500:5500
      - 8080:8080
    environment: 
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_ENABLE_XDB=true