-- up
CREATE TABLE tipos(
	id NUMBER(7) PRIMARY KEY,
	nombre VARCHAR2(20)
);

ALTER TABLE tipos ADD (
  CONSTRAINT tipos_pk PRIMARY KEY (ID));

CREATE SEQUENCE tipos_seq START WITH 1;

CREATE OR REPLACE TRIGGER tipos_pk 
BEFORE INSERT ON tipos 
FOR EACH ROW

BEGIN
  SELECT tipos_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

-- down

DROP SEQUENCE tipos_seq;
DROP TABLE tipos;