CREATE TABLE pokemones(
  ID NUMBER(7) PRIMARY KEY,
  NOMBRE VARCHAR2(20) NOT NULL,
    NUMERO NUMBER(3) NOT NULL,
    PESO FLOAT NOT NULL,
    TALLA FLOAT NOT NULL,
    IMAGEN VARCHAR(85),
    TIPO_ID NUMBER(7),
    FOREIGN KEY (TIPO_ID) REFERENCES TIPOS
);

ALTER TABLE pokemones ADD (
  CONSTRAINT pokemones_pk PRIMARY KEY (ID));

CREATE SEQUENCE pokemones_seq START WITH 1;

CREATE OR REPLACE TRIGGER pokemones_pk 
BEFORE INSERT ON pokemones 
FOR EACH ROW

BEGIN
  SELECT pokemones_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/